version: 2
updates:
  # Enable version updates for Python (pip)
  - package-ecosystem: "pip"
    # Look for `requirements.txt` files in the `root` directory
    directory: "/"
    # Check for updates every weekday
    schedule:
      interval: "daily"
      time: "07:00"  # Define o horário para verificar as atualizações

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
